name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release

      - name: Trigger Vercel Deploy
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
          -d '{}' \
          https://api.vercel.com/v1/integrations/deploy/prj_OMPpBqDsmLTiUTOAKtbaUaJGsHQ0/zUHB9DyIy8
